# 数组间的运算

In [14]:
import numpy as np
a = np.array([[1,2,3],[3,4,5]])
a

array([[1, 2, 3],
       [3, 4, 5]])

In [15]:
a + 3

array([[4, 5, 6],
       [6, 7, 8]])

In [16]:
a / 2

array([[0.5, 1. , 1.5],
       [1.5, 2. , 2.5]])

In [17]:
a * 3

array([[ 3,  6,  9],
       [ 9, 12, 15]])

In [18]:
# 注意和原生list不一样
a = [1,2,3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [19]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])
# arr1 + arr2 # 不可以进行计算
# arr1 + arr2

In [20]:
# 广播机制
# 数组在进行矢量化运算时，要求数组的形状是相等的。当形状不相等的数组执行算术运算的时候，就会出现广播机制，该机制会对数组进行扩展，使数组的shape属性值一样，这样，就可以进行矢量化运算了。
# 广播机制实现了时两个或两个以上数组的运算，即使这些数组的shape不是完全相同的，只需要满足如下任意一个条件即可。
#（1）如果两个数组的后缘维度（trailing dimension，即从末尾开始算起的维度）的轴长度相符，
#（2）或其中的一方的长度为1。
# 广播会在缺失和（或）长度为1的维度上进行。
# 广播机制需要扩展维度小的数组，使得它与维度最大的数组的shape值相同，以便使用元素级函数或者运算符进行运算。

In [21]:
arr1 = np.array([[0],[1],[2],[3]])
arr1.shape

(4, 1)

In [22]:
arr2 = np.array([1,2,3])
arr2.shape

(3,)

In [23]:
arr1+arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [24]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1], [3]])

In [25]:
arr1.shape

(2, 6)

In [26]:
arr2.shape

(2, 1)

In [27]:
arr2+arr1

array([[2, 3, 4, 3, 2, 5],
       [8, 9, 4, 5, 6, 4]])

# 矩阵运算

In [28]:
# 矩阵，matrix，和array的区别矩阵必须是2维的，但是array可以是多维的。
# 矩阵乘法api：
# np.matmul 
# np.dot 点乘


In [32]:
a = np.array([[80, 86],
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]])

In [33]:
b = np.array([[0.7], [0.3]])

In [34]:
b

array([[0.7],
       [0.3]])

In [36]:
# 矩阵乘法 - 点乘
np.dot(a,b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [37]:
# 矩阵乘法 
np.matmul(a,b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [38]:
c = 10 #常量

In [39]:
np.dot(c, a)

array([[800, 860],
       [820, 800],
       [850, 780],
       [900, 900],
       [860, 820],
       [820, 900],
       [780, 800],
       [920, 940]])

In [ ]:
# np.matmul(c, a)  # matmul不支持矩阵和标量的乘法