In [1]:
import numpy as np

In [3]:
# 生成10名同学，5门功课的数据
score = np.random.randint(40, 100, (10, 5))
score

array([[89, 98, 70, 58, 57],
       [68, 70, 99, 77, 73],
       [64, 92, 99, 98, 67],
       [92, 52, 57, 96, 95],
       [53, 93, 76, 96, 95],
       [92, 94, 58, 87, 92],
       [74, 94, 68, 58, 52],
       [69, 71, 40, 59, 93],
       [65, 73, 79, 91, 79],
       [66, 66, 53, 99, 55]])

In [7]:
# 取出最后4名同学的成绩，用于逻辑判断
# 从6开始
test_score = score[6:, 0:5]
test_score

array([[74, 94, 68, 58, 52],
       [69, 71, 40, 59, 93],
       [65, 73, 79, 91, 79],
       [66, 66, 53, 99, 55]])

In [8]:
# 逻辑判断, 如果成绩大于60就标记为True 否则为False
test_score > 60


array([[ True,  True,  True, False, False],
       [ True,  True, False, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True, False]])

In [9]:
test_score[test_score > 60] = 1
test_score

array([[ 1,  1,  1, 58, 52],
       [ 1,  1, 40, 59,  1],
       [ 1,  1,  1,  1,  1],
       [ 1,  1, 53,  1, 55]])

# 通用判断函数

In [10]:
# np.all():所有满足要求
np.all(score[0:2, :] > 60)

False

In [11]:
score

array([[89, 98, 70, 58, 57],
       [68, 70, 99, 77, 73],
       [64, 92, 99, 98, 67],
       [92, 52, 57, 96, 95],
       [53, 93, 76, 96, 95],
       [92, 94, 58, 87, 92],
       [ 1,  1,  1, 58, 52],
       [ 1,  1, 40, 59,  1],
       [ 1,  1,  1,  1,  1],
       [ 1,  1, 53,  1, 55]])

In [12]:
# np.any():其一满足要求
np.any(score[0:2, :] > 90)

True

In [13]:
# np.where（三元运算符）
# 通过使用np.where能够进行更加复杂的运算
# np.where()
temp = score[:4, :4]
np.where(temp > 60, 1, 0)

array([[1, 1, 1, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 0, 0, 1]])

In [14]:
# 复合逻辑需要结合np.logical_and和np.logical_or使用
# np.logical_and:逻辑与
np.where(np.logical_and(temp > 60, temp < 90), 1, 0)

array([[1, 0, 1, 0],
       [1, 1, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
# 逻辑或
np.where(np.logical_or(temp > 90, temp < 60), 1, 0)

array([[0, 1, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 1]])

# 统计运算

In [18]:
# 统计指标
# 在数据挖掘/机器学习领域，统计指标的值也是我们分析问题的一种方式。常用的指标如下：
# min(a, axis)
# Return the minimum of an array or minimum along an axis.最小值
# max(a, axis])
# Return the maximum of an array or maximum along an axis.最大值
# median(a, axis)
# Compute the median along the specified axis.中位数
# mean(a, axis, dtype)
# Compute the arithmetic mean along the specified axs.平均值
# std(a, axis, dtype)
# Compute the standard deviation along the specified axis.标准差
# var(a, axis, dtype)
# Compute the variance along the specified axis.方差
# 进行统计的时候，axis 轴的取值并不一定，Numpy中不同的API轴的值都不一样，在这里，axis 0代表列, axis 1代表行去进行统计
temp = score[:4, :]
temp

array([[89, 98, 70, 58, 57],
       [68, 70, 99, 77, 73],
       [64, 92, 99, 98, 67],
       [92, 52, 57, 96, 95]])

In [19]:
np.max(temp) #输出最大值

99

In [20]:
np.mean(temp) #平均值

78.55

In [21]:
np.max(temp, axis=0)

array([92, 98, 99, 98, 95])

In [22]:
np.max(temp, axis=1)

array([98, 99, 99, 96])

In [23]:
# 如果需要统计出某科最高分对应的是哪个同学？
# np.argmax(temp, axis=)
# np.argmin(temp, axis=)
np.argmax(temp)

7

In [24]:
np.argmax(temp, axis=0)

array([3, 0, 1, 2, 3])

In [25]:
np.argmin(temp, axis=0)

array([2, 3, 3, 0, 0])